services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    volumes:
      - Mealie-config:/app/data/

volumes:
  Mealie-config:
    external: true
