services:
  backup-sync:
    image: backup-sync:latest
    container_name: backup-sync
    environment:
      - URL=${URL_TEST}
      - USER=${USER}
      - PASS=${PASS}
      - CRYPT_PWD1=${CRYPT_PWD1}
      - CRYPT_PWD2=${CRYPT_PWD2}
    volumes:
      - ${MNT_PATH}:/mnt
    privileged: true
    devices:
      - "/dev/fuse:/dev/fuse"
    restart: no
