version: "3"

services:
  pihole:
    container_name: ${PIHOLE_NAME:-pihole}
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "${PIHOLE_HTTP_PORT:-80}:80/tcp"
    dns:
      - 127.0.0.1
    environment:
      TZ: 'France/Paris'
    volumes:
      - './backup/etc-pihole:/etc/pihole'
      - './backup/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
