services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: ${NAME:-wireguard}
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - PEERS=1
      - LOG_CONFS=true
    volumes:
      - ${CONFIG_PATH}:/config
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
