version: '3.3'

services:
  website:
    image: "website:latest"
    container_name: ${WEBSITE_NAME:-website}
    ports:
      - "${WEBSITE_PORT:-80}:80"
    volumes:
      - ${WEBSITE_SOURCE}:/var/www/html:ro
